baseurl = "http://esonghori.github.io"
languageCode = "en-us"
title = "Ebrahim Songhori"


[params]
	ProfilePicture = "/img/profile.jpg"
	Description = "Personal web-page"
	landingPageRedirectUrl = "/about/"
	AuthorName = "Ebrahim Songhori"
	github = "https://github.com/esonghori"
	linkedin = "https://www.linkedin.com/in/esonghori"
	twitter = "https://twitter.com/ebisonghori"
	facebook = "https://www.facebook.com/e.songhori"
	Copyright = ""
	[params.links]
		Publication = "/publication/"
		Resume = "/file/ebi-res.pdf"
		AboutMe = "/about/"
